<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * Cleanse all synthetic/mock data from the database (both locally and on Render deployment)
     * so that analytics and dashboards solely compute from authentic student applications and activity.
     */
    public function up(): void
    {
        // 1. Purge synthetic audit and auth logs generated by mock seeders
        if (Schema::hasTable('auth_logs')) {
            DB::table('auth_logs')
                ->where('ip_address', 'like', '10.24.%')
                ->delete();
        }

        if (Schema::hasTable('admin_action_logs')) {
            DB::table('admin_action_logs')
                ->where('ip_address', '10.24.132.49')
                ->delete();
        }

        if (Schema::hasTable('config_change_logs')) {
            DB::table('config_change_logs')
                ->where('ip_address', '10.24.132.49')
                ->delete();
        }

        if (Schema::hasTable('export_access_logs')) {
            DB::table('export_access_logs')
                ->where('ip_address', '10.24.132.49')
                ->delete();
        }

        // 2. Purge synthetic mock students created with mock email pattern e.g. from DashboardMockSeeder
        if (Schema::hasTable('users')) {
            // Find any mock students whose emails match the DashboardMockSeeder pattern (e.g. alphanumeric names ending in @clsu2.edu.ph with numbers)
            // But safely ensure we only target synthetic accounts if any exist
            $mockUserIds = DB::table('users')
                ->where('role', 'student')
                ->where('name', 'like', '% [1-9][0-9]')
                ->pluck('id');

            if ($mockUserIds->isNotEmpty()) {
                if (Schema::hasTable('a_i_results') && Schema::hasTable('documents')) {
                    $docIds = DB::table('documents')
                        ->whereIn('uploaded_by', $mockUserIds)
                        ->pluck('id');
                    if ($docIds->isNotEmpty()) {
                        DB::table('a_i_results')->whereIn('document_id', $docIds)->delete();
                    }
                }

                if (Schema::hasTable('documents')) {
                    DB::table('documents')->whereIn('uploaded_by', $mockUserIds)->delete();
                }

                if (Schema::hasTable('status_logs')) {
                    DB::table('status_logs')->whereIn('changed_by', $mockUserIds)->delete();
                }

                if (Schema::hasTable('email_logs')) {
                    DB::table('email_logs')->whereIn('application_id', function ($query) use ($mockUserIds) {
                        $query->select('id')->from('applications')->whereIn('user_id', $mockUserIds);
                    })->delete();
                }

                if (Schema::hasTable('applications')) {
                    DB::table('applications')->whereIn('user_id', $mockUserIds)->delete();
                }

                if (Schema::hasTable('student_profiles')) {
                    DB::table('student_profiles')->whereIn('user_id', $mockUserIds)->delete();
                }

                DB::table('users')->whereIn('id', $mockUserIds)->delete();
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Irreversible cleanup of synthetic/mock data
    }
};
