<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Arial', sans-serif; background-color: #f4f7f6; padding: 20px; }
        .email-container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }
        .header { background-color: #0F5934; color: #ffffff; padding: 20px; text-align: center; border-bottom: 4px solid #F2A900; }
        .content { padding: 30px; color: #333333; line-height: 1.6; }
        .status-badge { display: inline-block; padding: 8px 15px; border-radius: 4px; font-weight: bold; color: white; margin: 15px 0; }
        .approved { background-color: #198754; }
        .rejected { background-color: #dc3545; }
        .footer { background-color: #f8f9fa; padding: 15px; text-align: center; font-size: 12px; color: #6c757d; border-top: 1px solid #eeeeee; }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <h2 style="margin: 0;">A.E.G.I.S. Portal</h2>
            <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.9;">Office of Student Affairs | CLSU</p>
        </div>
        
        <div class="content">
            <p>Dear Applicant,</p>
            <p>This is an official notification regarding your scholarship application for the <strong>{{ $application->program_name }}</strong>.</p>
            
            <p>After a thorough review and digital forensics verification by the A.E.G.I.S. system, your application status has been updated to:</p>
            
            <div style="text-align: center;">
                @if($application->status == 'Approved')
                    <span class="status-badge approved">APPROVED</span>
                    <p>Congratulations! Your academic documents have been verified as authentic and you are eligible for the grant.</p>
                @else
                    <span class="status-badge rejected">REJECTED</span>
                    <p>Unfortunately, your application was denied. If your document flagged high for digital forgery, you may face disciplinary action. Please contact the OSA immediately.</p>
                @endif
            </div>

            <p style="margin-top: 30px;">Reference ID: <strong>APP-{{ $application->id }}</strong><br>
            Declared GWA: <strong>{{ $application->gwa }}</strong></p>
        </div>

        <div class="footer">
            <p>This is an automated message generated by the A.E.G.I.S. System. Please do not reply directly to this email.</p>
            <p>&copy; {{ date('Y') }} Central Luzon State University.</p>
        </div>
    </div>
</body>
</html>